### ISSUE TITLE
support for -t option

### ISSUE THREAD

**Issue by waxie** [walterdejong/firewater#12]
Firewater cannot handle iptables rules with the -t option.

For example the iptable command:

<code>iptables -t nat -A POSTROUTING -o iface -j MASQUERADE</code>

setting in firewater rules:

<code>echo -t nat -A POSTROUTING -o iface -j MASQUERADE</code>

will fail:

<pre><code>root# /etc/init.d/firewater commit
Starting firewater hostbased firewall ...
iptables-restore v1.4.8: Line 25 seems to have a -t table option.

Error occurred at line: 25
Try `iptables-restore -h' or 'iptables-restore --help' for more information.</code></pre>

iptables-restore can not handle the -t option.

To restore nat/routing iptables, the input for iptables-restore should look like this for example:

<pre><code>*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A POSTROUTING -o iface -j MASQUERADE
COMMIT</code></pre>

**Comment by walterdejong** [comment]
That is a good workaround.

Also, firewater version 2 has good NAT support.
firewater 2 is a full rewrite at https://gitlab.com/surfsara/firewater
